databases:
  - name: uvhezawu
    databaseName: uvhezawu
    user: uvhezawu

services:
  - type: web
    name: rent_for_a_day
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uvhezawu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false